baseURL = "http://www.polarize.pw/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "Equation Sheets"

theme = "LoveIt"

[params]
  # theme version
  version = "0.2.X"
  [params.header.title]
    # URL of the LOGO
    # LOGO 的 URL
    logo = ""
    # title name
    # 标题名称
    name = "Equation Sheets"
  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = ""
      # title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page
      subtitle = ""
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 20
      # display image-preview
      imagePreview = true
  # Social config in home page
  [params.social]
    GitHub = ""
    Linkedin = ""
    Youtubechannel = ""
    Googlescholar = ""
    Researchgate = ""
    Email = ""
    RSS = false
  # Footer config
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    custom = '<a href="https://github.com/tengjuilin/equation-sheets"><i class="fab fa-github fa-fw"></i></a>'
    # whether to show Hugo and theme info
    hugo = false
    # whether to show copyright info
    copyright = true
    # whether to show the author
    author = true
    # site creation time
    since = 2020
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a>'
  [params.section]
    # special amount of posts in each section page
    paginate = 100
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 20
  [params.list]
    # special amount of posts in each list page
    paginate = 100
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 20
  [params.page.comment]
    enable = false
  [params.page.math]
    enable = true
    copyTex = true
    mhchem = true
    # default block delimiter is $$ ... $$ and \\[ ... \\]
    blockLeftDelimiter = "$$"
    blockRightDelimiter = "$$"
    # default inline delimiter is $ ... $ and \\( ... \\)
    inlineLeftDelimiter = "$"
    inlineRightDelimiter = "$"
  [params.page.toc]
    enable = true
    auto = true
  # Mapbox GL JS config (Mapbox GL JS https://docs.mapbox.com/mapbox-gl-js)
  [params.page.mapbox]
    # access token of Mapbox GL JS
    # Mapbox GL JS 的 access token
    accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
    # style for the light theme
    lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
    # style for the dark theme
    darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
    # whether to add NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
    navigation = true
    # whether to add GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
    geolocate = true
    # whether to add ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
    scale = true
    # whether to add FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
    fullscreen = true

[menu]
  # [[menu.main]]
  #   identifier = "cv"
  #   # you can add extra information before the name (HTML format is supported), such as icons
  #   pre = ""
  #   # you can add extra information after the name (HTML format is supported), such as icons
  #   post = ""
  #   name = "CV"
  #   url = "/cv/"
  #   # title will be shown when you hover on this menu link
  #   title = "CV"
  #   weight = 1
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    url = "https://github.com/tengjuilin/equation-sheets"
    title = "GitHub"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[author]
  name = "Teng-Jui Lin"
  link = "https://github.com/tengjuilin"

[module]
  [module.hugoVersion]
    extended = true
